database:
  type: "sqlite"
  host: "localhost"
  port: 3306
  name: "enchanted_wanted"
  username: "root"
  password: ""
kill-commands:
  - "[PLAYER] command"
  - "[CONSOLE] command"
wanted:
  max: 6
  filled: "&c★"
  empty: "&7✩"
  number: "&e"