name: EnchantedWanted
version: '1.0'
main: org.yashar.enchantedWanted.EnchantedWanted
api-version: '1.20'
load: POSTWORLD
author: "IRDevs"
description: 'Enchanted Wanted is a Plugin For GTA Servers'
commands:
  wanted:
    description: Aha
  wanteds:
    description: With this command you can get your wanted
softdepend:
  - PlaceholderAPI
  - GPS
  - CuffEm
  - BetterJails