name: EnchantedWanted
version: '1.0'
main: org.yashar.enchantedWanted.EnchantedWanted
api-version: '1.21'
load: POSTWORLD
author: IRDevs
description: 'a Simple Plugin For GTA Servers!'
softdepend:
  - PlaceholderAPI
  - GPS
  - CuffEm